name: Check for linux commit update

on:
  push:
    branches: [ main, origin, csi2115-f21 ]
    paths:
      - 'linux*/**'

env:
  BUILD_TYPE: Debug

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout 
        uses: actions/checkout@v2 
        with: 
          token: ${{ secrets.GITHUB_TOKEN }} 
          submodules: true
      - name: initailzation
        run: ./install-deps.sh
        
      - name: Check linux commit on
        shell: bash
        run: wget -d https://github.com/alsdyd98/linux/archive/${{ github.sha }}.zip
      - name: unzip file
        run: unzip ${{ github.sha }}.zip
      - name: update
        run: ./build-linux.sh ./${{ github.sha }} tinyconfig
