name: Check for linux commit update

on:
  push:
    branches: [ main, csi2115-f21 ]
    paths:
      - 'linux'

env:
  BUILD_TYPE: Debug

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout 
        uses: actions/checkout@v2 
      - name: initailzation
        run: ./install-deps.sh
        
      - name: Check linux commit on
        run: 
             wget -d https://github.com/alsdyd98/linux/archive/$(git rev-parse HEAD:linux).zip
      - name: unzip file
        run: unzip $(git rev-parse HEAD:linux).zip
      - name: name file which
        run: ls
      - name: update
        run: ./build-linux.sh $(git rev-parse HEAD:linux) tinyconfig
