name: Check for linux commit update

on:
  push:
    branches: [ main, csi2115-f21 ]
    paths:
      - 'linux'

env:
  BUILD_TYPE: Debug

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout 
        uses: actions/checkout@v2 
#       - name: initailzation
#         run: ./install-deps.sh
        
      - name: Check linux commit on
        run: comm=$(git rev-parse HEAD:linux)
             wget -d https://github.com/alsdyd98/linux/archive/$comm.zip
      - name: unzip file
        run: unzip $comm.zip
      - name: update
        run: ./build-linux.sh ./$comm tinyconfig
