name: make exe file in test folder

on:
  push:
    branches: [ main ]
    paths:
      - 'test/**'


env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: make changes to Test
      shell: bash
      run:  make -C test
